import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	main_container: {
		backgroundColor: "white",
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	header: {
		position: "absolute",
		top: 80,
		left: 30,
		flexDirection: "row",
	},
	header_txt: {
		color: "black",
		fontWeight: "bold",
		fontSize: 32,
		paddingLeft: 10,
	},
	subheader: {
		color: "black",
		position: "absolute",
		top: 130,
		left: 30,
		fontSize: 15,
	},
	container:{
		height: 120,
		width: 350,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 20,
		padding: 10,
		backgroundColor: "#374C7A",
		position: "absolute",
	},
	container_top: {
		top: 190,
		left: 20,
	},
	container_second:{
		top: 320,
		left: 20,
	},
	container_third:{
		top: 450,
		left: 20,
	},
	container_fourth:{
		top: 580,
		left: 20,
	},
	court_title: {	
		color: "white",
		fontSize: 20,
		fontFamily: "Poppins",
		paddingBottom: 10,
		fontWeight: "bold",
	},
	location:{
		flexDirection: "row",
	},
	court_data:{
		color: "white",
		fontSize: 17,
		fontFamily: "Poppins",
		paddingBottom: 10,
		paddingLeft: 10,	
	},
	booking:{
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		height: 35,
		width: 100,
		borderWidth: 1,
		borderColor: "white",
		borderRadius: 20,
		backgroundColor: "white",
		top: 70,
		right: 10,
	},
	booking_txt:{
		color: "#374C7A",
		fontSize: 15,
		fontFamily: "Poppins",
		fontWeight: "bold",
	},
	available:{
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		height: 35,
		width: 100,
		borderWidth: 1,
		borderColor: "green",
		borderRadius: 20,
		backgroundColor: "green",
		top: 70,
		right: 120,
	},
	booked:{
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		height: 35,
		width: 100,
		borderWidth: 1,
		borderColor: "red",
		borderRadius: 20,
		backgroundColor: "red",
		top: 70,
		right: 120,
	},
	availability_txt:{
		color: "white",
		fontSize: 15,
		fontFamily: "Poppins",
		fontWeight: "bold",
	},

});
