import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	main_container: {
		backgroundColor: "white",
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		gap: 20,
	},
	upper:{
		height: 500,
		width: 400,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 0,
		padding: 10,
		backgroundColor: "#374C7A",
		position: "absolute", 
		bottom: 500,
	},
	back:{
		position: "absolute",
		top: 200,
		left: 15,
		flexDirection: "row",
	},
	court_location: {
		color: "black",
		fontSize: 15,
		fontFamily: "Poppins",
		paddingLeft: 8,
	},
	location: {
		flexDirection: "row",
		position: "absolute",
		top: 400,
		left: 27,
	},
	court_name:{
		color: "black",
		fontSize: 25,
		fontFamily: "Poppins",
		fontWeight: "bold",
		position: "absolute",
		top: 360,
		left: 10,
	},
	court_data: {
		color: "black",
		fontSize: 15,
		fontFamily: "Inter",
		paddingLeft: 10,
		paddingRight: 10,
		position: "absolute",
		top: 450,
		left: 10,
		right: 10,
	},
	book_btn: {	
		backgroundColor: "#374C7A",
		padding: 15,
		borderRadius: 12,
		alignItems: "center",
		width: 250,
		position: "absolute",
		bottom: 150,
	},
	book_btn_text: {
		color: "white",
		fontSize: 20,
		fontWeight: "bold",
	},
});
